engines:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
    - "**.ts"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
    - "**.rb"

exclude_paths:
  - bin
  - node_modules
  - typings
  - coverage
  - dist
  - test