language: node_js
node_js: "node"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false

    - os: osx
      osx_image: xcode7.3
      sudo: false
      
git:
  depth: 3

addons:
  apt:
    packages:
      - rpm

cache:
  directories:
    - node_modules

install:
  - npm install
  - cd packages/vc-youku-plugin
  - npm install

script:
  - npm run make
