language: node_js
node_js: node
dist: trusty
sudo: false
git:
  depth: 3
addons:
  apt:
    packages:
    - rpm
cache:
  directories:
  - node_modules
install:
- npm install
- cd packages/vc-youku-plugin
- npm install
script:
- npm test
after_script:
- if [ ${TRAVIS_TAG} ]; then npm run publish -- --tag="${TRAVIS_TAG}"; fi
