language: node_js
node_js: node
os:
- linux
- osx
dist: trusty
sudo: true
git:
  depth: 3
addons:
  apt:
    packages:
    - rpm
cache:
  directories:
  - node_modules
install:
- npm install
script:
- ./script/travis-test.sh
after_script:
- if [ ${TRAVIS_TAG} ]; then npm run publish; fi
